import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modal: {
    margin: 0,
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 28,
    paddingTop: 20,
  },
  slideSection: {
    width: 64,
    height: 4,
    backgroundColor: "#C1C1C1",
    alignSelf: "center",
    borderRadius: 12,
    marginBottom: 37,
  },
  commentSection: { paddingLeft: 17, paddingRight: 17 },
  modalContent: {
    marginBottom: 18,
    gap: 8,
  },
  input: {
    height: 30,
    borderRadius: 9,
    borderColor: "transparent",
    borderWidth: 1.5,
    width: "84%",
  },
  keyboard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 42,
    borderRadius: 9,
    borderColor: "#E8E9E8",
    borderWidth: 1.5,
    paddingLeft: 16,
    paddingRight: 16,
    marginBottom: 10,
  },
  button: {
    borderRadius: 8,
    borderColor: "#1F1F1F",
    backgroundColor: "#FFA851",
    borderWidth: 1,
    color: "#000",
  },
  buttonText: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 6,
    paddingBottom: 6,
    fontSize: 12,
    fontFamily: "SUITE_Bold",
    color: "#1F1F1F",
  },
  comment: {
    fontSize: 15,
    color: "#1F1F1F",
    fontFamily: "SUITE_Medium",
  },
  subComment: {
    fontSize: 10,
    color: "#C1C1C1",
    fontFamily: "SUITE",
  },
  secretCommentSection: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 3,
  },
  secretComment: {
    color: "#5C5C5C",
    fontSize: 10,
    fontFamily: "SUITE_Bold",
  },
  childrenSection: {
    flexDirection: "row",
    gap: 8,
    paddingLeft: 80,
    marginTop: 4,
    marginBottom: 15,
  },
  authorBox: {
    backgroundColor: "#6ADCA3",
    borderRadius: 12,
    alignSelf: "center",
  },
  author: {
    color: "#1F1F1F",
    fontSize: 10,
    paddingRight: 5,
    paddingLeft: 5,
    paddingTop: 4,
    paddingBottom: 4,
    fontFamily: "SUITE_Medium",
  },
  privateImg: { alignSelf: "center", width: 16, height: 16 },
  profileImg: {
    width: 32,
    height: 32,
    borderRadius: 50,
  },
  secretImg: { width: 12, height: 12, alignSelf: "center" },
});
