import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "space-between",
    backgroundColor: "#FFFBF6",
  },
  messagesContainer: {
    flex: 1,
    paddingRight: 20,
    paddingLeft: 20,
  },
  message: {
    padding: 10,
    marginVertical: 5,
    borderRadius: 9,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderColor: "#1F1F1F",
    backgroundColor: "#fff",
    flex: -1,
    alignSelf: "flex-end",
    maxWidth: "60%",
  },
  friendMessage: {
    marginVertical: 5,
    borderRadius: 9,
    borderTopLeftRadius: 0,
    borderWidth: 1,
    borderColor: "#1F1F1F",
    padding: 10,
    backgroundColor: "#E8E9E8",
    flex: -1,
    alignSelf: "flex-start",
    maxWidth: "60%",
    marginLeft: 49,
    bottom: 25,
  },
  inputContainer: {
    flexDirection: "row",
    padding: 10,
    borderColor: "#C1C1C1",
    borderWidth: 1.5,
    borderRadius: 8,
    marginBottom: 19,
    backgroundColor: "#fff",
  },
  input: {
    flex: 1,
    fontSize: 12,
    fontWeight: 700,
    color: "#5C5C5C",
  },
  icon: {
    width: 20,
    height: 21,
    marginLeft: 10,
  },
  time: {
    fontSize: 10,
    fontWeight: 500,
    color: "#C1C1C1",
    alignSelf: "flex-end",
    marginBottom: 25,
  },
  inputSection: {
    paddingLeft: 22,
    paddingRight: 22,
    paddingTop: 20,
    backgroundColor: "#fff",
  },
  friendsName: {
    fontSize: 10,
    fontWeight: 700,
    color: "#1F1F1F",
    paddingTop: 3,
  },
  noti: {
    flex: 1,
    fontSize: 12,
    fontWeight: 700,
    color: "#5C5C5C",
    textAlign: "center",
  },
  date: {
    fontSize: 15,
    fontWeight: 700,
    color: "#1F1F1F",
    fontFamily: "SUITE_Bold",
  },
  dateSection: {
    backgroundColor: "#6ADCA3",
    borderWidth: 3,
    borderBottomWidth: 4.5,
    borderRightWidth: 4.5,
    borderColor: "#1F1F1F",
    borderRadius: 55,
    paddingBottom: 9,
    paddingTop: 9,
    paddingRight: 18,
    paddingLeft: 18,
  },
  topSection: {
    alignItems: "center",
    gap: 16,
    paddingBottom: 60,
    paddingTop: 68,
  },
});
